- hosts: all
  tasks:
    - name: Hello Message JUN
      debug:
        msg: "Hello World JUN!"
        
#    - name: Check if Named is running
#      systemd:
#        state: started
#        name: named
    - name: install the latest version of Apache
      yum:
        name: httpd
        state: latest
        
    - name: Hello Message JUN2
      debug:
        msg: "Hello World JUN2!"
